core/urls.py
from django.urls import path
from core import views


app_name = "core"

urlpatterns = [
    path("", views.home, name="home")
]

io_app/apps/core/urls.py
from django.urls import path
from io_app.apps.core import views


app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("page/<str:page_id>/", views.home, name="home"),
    path("directories/", views.directories, name="directories"),
    path("directories/page/<str:page_id>/", views.directories, name="directories"),
    path("directories/<str:directory_uuid>/", views.directory_content, name="directory_content"),
    path("directories/<str:directory_uuid>/<str:page_id>/", views.directory_content, name="directory_content"),
    path("shared_directories/", views.shared_directories, name="shared_directories"),
    path("processes/", views.processes, name="processes"),
    path("processes/start_archive_extraction_process/start/", views.start_archive_extraction_process,
         name="start_archive_extraction_process"),
    path("processes/start_directory_compression_process/start/", views.start_directory_compression_process,
         name="start_directory_compression_process"),
    path("processes/start_video_compatibility_conversion_process/start/",
         views.start_video_compatibility_conversion_process,
         name="start_video_compatibility_conversion_process"),
]

io_app/apps/storage_manager/urls.py
from django.urls import path
from io_app.apps.storage_manager.views import files_views, directories_views


app_name = "storage_manager"

urlpatterns = [
    path("upload/", files_views.upload, name="upload"),
    path("upload_file/", files_views.upload_file, name="upload_file"),
    path("files/<str:file_uuid>/", files_views.preview, name="preview"),
    path("files/<str:file_uuid>/download/", files_views.download_file, name="download_file"),
    path("files/<str:file_uuid>/remove/", files_views.remove_file, name="remove_file"),
    path("files/<str:file_uuid>/toggle_access_via_link/", files_views.toggle_access_via_link,
         name="toggle_access_via_link"),
    path("files/<str:file_uuid>/preview/", files_views.preview_raw, name="preview_raw"),
    path("files/<str:file_uuid>/stream/", files_views.stream_media_file, name="stream_media_file"),
    path("files/<str:file_uuid>/management/", files_views.file_management, name="file_management"),
    path("files/<str:file_uuid>/change_directory/", files_views.change_directory, name="change_directory"),
    path("files/<str:file_uuid>/change_name/", files_views.file_change_name, name="file_change_name"),
    path("directories/add", directories_views.add_directory, name="add_directory"),
    path("directories/<str:directory_uuid>/management/", directories_views.directory_management,
         name="directory_management"),
    path("directories/<str:directory_uuid>/remove/", directories_views.remove_directory,
         name="remove_directory"),
    path("directories/<str:directory_uuid>/update_files/", directories_views.update_directory_files,
         name="update_directory_files"),
    path("directories/<str:directory_uuid>/share_directory_to_user/", directories_views.share_directory_to_user,
         name="share_directory_to_user"),
    path("directories/<str:directory_uuid>/remove_directory_from_shared/", directories_views.remove_directory_from_shared,
         name="remove_directory_from_shared"),
    path("directories/<str:directory_uuid>/change_name/", directories_views.directory_change_name,
         name="directory_change_name"),
]

io_app/urls.py
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path("", include("io_app.apps.core.urls")),
    path("auth/", include("io_app.apps.authenticate.urls")),
    path("storage/", include("io_app.apps.storage_manager.urls")),
    path("api/", include("io_app.apps.api.urls")),
]


if settings.DEBUG or settings.ADMIN_ENABLED:
    from django.contrib import admin

    admin.site.site_header = "IO admin"
    admin.site.index_title = "IO admin"
    admin.site.site_title = "IO admin"

    urlpatterns.append(path('admin/', admin.site.urls))


handler404 = "io_app.apps.core.error_views.not_found"
handler500 = "io_app.apps.core.error_views.server_error"
handler400 = "io_app.apps.core.error_views.bad_request"

io_app/apps/storage_manager/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import resolve_url
from datetime import datetime
from io_app.consts import MediaConsts
from io_app.utils import files_utils


class Directory(models.Model):
    name = models.CharField(max_length=200, unique=False, null=False)
    uuid = models.CharField(max_length=32, unique=True, null=False, default=files_utils.generate_uuid)

    creation_date = models.DateTimeField(unique=False, null=False, default=datetime.utcnow)

    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="directories")
    shared_to_users = models.ManyToManyField(get_user_model(), related_name="shared_directories", blank=True)

    def __str__(self):
        return self.uuid

    def get_size(self):
        return sum([file.size for file in self.files.all()])

    def get_size_in_mb(self):
        return round((self.get_size() / MediaConsts.BYTES_IN_MB), 2)

    def get_files_count(self):
        return len(self.files.all())


class File(models.Model):
    name = models.CharField(max_length=200, unique=False, null=False)
    uuid = models.CharField(max_length=32, unique=True, null=False)

    extension = models.CharField(max_length=10, unique=False, null=False)
    size = models.IntegerField(unique=False, null=False)

    upload_date = models.DateTimeField(unique=False, null=False, default=datetime.utcnow)

    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="files")
    directory = models.ForeignKey(Directory, on_delete=models.CASCADE, related_name="files", blank=True, null=True)

    accessible_via_link = models.BooleanField(default=False)

    def __str__(self):
        return self.uuid

    def get_file_size_in_mb(self):
        return round((self.size / MediaConsts.BYTES_IN_MB), 2)

    def get_directory_name(self):
        return self.directory.name if self.directory else "root"

    def get_directory_url(self):
        url = resolve_url("core:directory_content", directory_uuid=self.directory.uuid) \
            if self.get_directory_name() != "root" else resolve_url("core:home")

        return url

    def check_if_shared_to_user(self, user):
        shared = False

        if self.directory and user in self.directory.shared_to_users.all():
            shared = True

        return shared

    def can_be_previewed(self):
        can_be_previewed = False

        if self.extension in MediaConsts.CAN_BE_PREVIEWED_EXTENSIONS:
            can_be_previewed = True

        return can_be_previewed

io_app/apps/storage_manager/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from io_app.consts import MessagesConsts
from io_app.apps.storage_manager import models


class AddDirectoryForm(forms.Form):
    directory_name = forms.CharField(label="", max_length=25, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "directory name"
    }))

    template_name = "components/form.html"

    def clean_directory_name(self):
        data = self.cleaned_data["directory_name"]
        directory = models.Directory.objects.filter(owner=self.user, name=data).first()

        if directory:
            raise ValidationError(MessagesConsts.DIRECTORY_EXISTS)

        return data


class ChangeDirectoryForm(forms.Form):
    directory_name = forms.ChoiceField(label="", widget=forms.Select(attrs={
        "class": "form-select",
    }))

    template_name = "components/form.html"

    def clean_directory_name(self):
        data = self.cleaned_data["directory_name"]

        if data != "root":
            directory = models.Directory.objects.filter(owner=self.user, name=data).first()

            if not directory:
                raise ValidationError(MessagesConsts.DIRECTORY_DOESNT_EXIST)

        return data


class ChangeDirectoryNameForm(forms.Form):
    directory_name = forms.CharField(label="", max_length=200, widget=forms.TextInput(attrs={
        "class": "form-control",
    }))

    template_name = "components/form.html"

    def clean_directory_name(self):
        data = self.cleaned_data["directory_name"]
        directory = models.Directory.objects.filter(owner=self.user, name=data).first()

        if directory:
            raise ValidationError(MessagesConsts.DIRECTORY_EXISTS)

        return data


class ChangeFileNameForm(forms.Form):
    file_name = forms.CharField(label="", max_length=200, widget=forms.TextInput(attrs={
        "class": "form-control",
    }))

    template_name = "components/form.html"

    def clean_file_name(self):
        data = self.cleaned_data["file_name"]
        file = models.File.objects.filter(owner=self.user, name=data).first()

        if file:
            raise ValidationError(MessagesConsts.FILE_EXISTS)

        return data


class UpdateDirectoryFilesForm(forms.Form):
    files = forms.MultipleChoiceField(label="", widget=forms.CheckboxSelectMultiple(attrs={
        "class": "checkboxes-wrapper",
    }))

    template_name = "components/form.html"

    def clean_files(self):
        data = self.cleaned_data["files"]

        for file_name in data:
            file = models.File.objects.filter(owner=self.user, name=file_name).first()

            if not file:
                raise ValidationError(MessagesConsts.FILE_DOESNT_EXIST)

        return data


class ShareDirectoryToUserForm(forms.Form):
    username = forms.CharField(label="", max_length=25, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "username"
    }))

    template_name = "components/form.html"

    def clean_username(self):
        data = self.cleaned_data["username"]
        user = get_user_model().objects.filter(username=data).first()

        if not user:
            raise ValidationError(MessagesConsts.USER_DOESNT_EXIST)

        if user and user == self.user:
            raise ValidationError(MessagesConsts.USER_DOESNT_EXIST)

        return data

io_app/apps/storage_manager/views/directories_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from io_app.apps.storage_manager import models
from io_app.consts import MessagesConsts
from io_app.apps.storage_manager import forms
import logging


logger = logging.getLogger(settings.LOGGER_NAME)


@login_required
@require_http_methods(["GET", "POST"])
def add_directory(request):
    form = forms.AddDirectoryForm(data=request.POST or None)

    if request.method == "POST":
        form.user = request.user

        if form.is_valid():
            directory_name = form.cleaned_data["directory_name"]
            models.Directory(name=directory_name, owner=request.user).save()

            messages.add_message(request, messages.SUCCESS, MessagesConsts.DIRECTORY_ADDED)

            return redirect("core:directories")

    return render(request, "add_directory.html", {"form": form})


@login_required
@require_http_methods(["GET"])
def directory_management(request, directory_uuid):
    directory = get_object_or_404(models.Directory, uuid=directory_uuid, owner=request.user)

    change_directory_name_form = forms.ChangeDirectoryNameForm()
    change_directory_name_form.fields["directory_name"].initial = directory.name

    update_files_form = forms.UpdateDirectoryFilesForm()
    directory_files = [(file.name, file.name) for file in directory.files.all()]
    all_files = [(file.name, file.name) for file in request.user.files.filter(directory=None).all()]

    update_files_form.fields["files"].choices = directory_files + all_files
    update_files_form.fields["files"].initial = [name[0] for name in directory_files]

    share_to_user_form = forms.ShareDirectoryToUserForm()
    share_to_user_form.user = request.user

    context = {
        "directory": directory,
        "update_files_form": update_files_form,
        "share_to_user_form": share_to_user_form,
        "change_directory_name_form": change_directory_name_form,
    }

    return render(request, "directory_management.html", context)


@login_required
@require_http_methods(["POST"])
def remove_directory(request, directory_uuid):
    directory = get_object_or_404(models.Directory, uuid=directory_uuid, owner=request.user)
    directory.delete()

    messages.add_message(request, messages.SUCCESS, MessagesConsts.DIRECTORY_REMOVED_SUCCESSFULLY)

    return redirect("core:directories")


@login_required
@require_http_methods(["POST"])
def update_directory_files(request, directory_uuid):
    directory = get_object_or_404(models.Directory, uuid=directory_uuid, owner=request.user)

    form = forms.UpdateDirectoryFilesForm(data=request.POST)
    form.user = request.user

    directory_files = [(file.name, file.name) for file in directory.files.all()]
    all_files = [(file.name, file.name) for file in request.user.files.filter(directory=None).all()]

    form.fields["files"].choices = directory_files + all_files

    if form.is_valid():
        files = form.cleaned_data["files"]

        files_models = [file for file in request.user.files.all() if file.name in files]

        directory.files.set(files_models)
        directory.save()

        messages.add_message(request, messages.SUCCESS,
                             MessagesConsts.UPDATED_DIRECTORY_FILES.format(files_count=len(files_models)))

    return redirect("storage_manager:directory_management", directory_uuid=directory_uuid)


@login_required
@require_http_methods(["POST"])
def share_directory_to_user(request, directory_uuid):
    directory = get_object_or_404(models.Directory, uuid=directory_uuid, owner=request.user)

    form = forms.ShareDirectoryToUserForm(data=request.POST)
    form.user = request.user

    if form.is_valid():
        username = form.cleaned_data["username"]
        user = get_user_model().objects.filter(username=username).first()

        if user not in directory.shared_to_users.all():
            user.shared_directories.add(directory)
            user.save()

            messages.add_message(request, messages.SUCCESS, MessagesConsts.SHARED_TO_USER.format(
                obj_name=directory.name, username=username))

        else:
            messages.add_message(request, messages.ERROR, MessagesConsts.DIRECTORY_ALREADY_SHARED_TO_USER)

    else:
        messages.add_message(request, messages.ERROR, MessagesConsts.ERROR_WHILE_SHARING_DIRECTORY_TO_USER)

    return redirect("storage_manager:directory_management", directory_uuid=directory_uuid)


@login_required
@require_http_methods(["POST"])
def remove_directory_from_shared(request, directory_uuid):
    directory = get_object_or_404(models.Directory, uuid=directory_uuid, owner=request.user)

    username = request.POST["username"]
    user = get_user_model().objects.filter(username=username).first()

    if user:
        if user in directory.shared_to_users.all():
            user.shared_directories.remove(directory)
            user.save()

            messages.add_message(request, messages.SUCCESS, MessagesConsts.REMOVE_SHARED_TO_USER.format(
                obj_name=directory.name, username=user.username))

        else:
            messages.add_message(request, messages.ERROR, MessagesConsts.DIRECTORY_NOT_SHARED_TO_USER)
    else:
        messages.add_message(request, messages.ERROR, MessagesConsts.USER_DOESNT_EXIST)

    return redirect("storage_manager:directory_management", directory_uuid=directory_uuid)


@login_required
@require_http_methods(["POST"])
def directory_change_name(request, directory_uuid):
    directory = get_object_or_404(models.Directory, uuid=directory_uuid, owner=request.user)

    form = forms.ChangeDirectoryNameForm(data=request.POST)
    form.user = request.user

    if form.is_valid():
        directory_name = form.cleaned_data["directory_name"]

        directory.name = directory_name
        directory.save()

        messages.add_message(request, messages.SUCCESS, MessagesConsts.CHANGED_DIRECTORY_NAME)

    else:
        messages.add_message(request, messages.ERROR, MessagesConsts.ERROR_WHILE_CHANGING_DIRECTORY_NAME)

    return redirect("storage_manager:directory_management", directory_uuid=directory_uuid)

io_app/apps/storage_manager/templates/add_directory.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}

<div class="centered-container">
    <form method="POST">
        {% csrf_token %}
        {{ form }}

        <button class="accept-button btn login-button" type="submit">
            Add
        </button>
    </form>
</div>

{% endblock %}

io_app/apps/storage_manager/templates/directory_management.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}
    <!-- Remove Modal -->
    {% include "components/modals/remove_directory_modal.html" with directory=directory %}

    <!-- Page content -->
    <div class="page-content-wrapper mb-3">
        <div class="content-wrapper">
            <a class="directory-name" data-bs-toggle="collapse" href="#changeDirectoryNameCollapsible" role="button"
               aria-expanded="false" aria-controls="changeDirectoryNameCollapsible">
                <h3>
                    {{directory.name}}
                </h3>
            </a>
            <div class="file-details-wrapper">
              <span>
                  <b>UUID:</b> {{directory.uuid}}
              </span>
              <span>
                  <b>Size:</b> {{directory.get_size_in_mb}}MB</span>
              </span>
              <span>
                  <b>Files:</b> {{directory.get_files_count}}</span>
              </span>
              <span>
                  <b>Creation date:</b> {{directory.creation_date|date:'d-m-Y G:i'}}</span>
              </span>
              <span>
                  <b>Shared to users:</b> {{directory.shared_to_users|length}}</span>
              </span>
            </div>
            <div class="file-details-controls-wrapper">
              <a class="btn btn-secondary" href="{% url 'core:directory_content' directory_uuid=directory.uuid %}" role="button" target="_blank">
                  Open
              </a>
              <button type="button" class="btn btn-danger" data-bs-target="#removeDirectoryModal" data-bs-toggle="modal">
                  Remove
              </button>
            </div>
        </div>
        <div class="content-wrapper collapse" id="changeDirectoryNameCollapsible">
            <form method="POST" action="{% url 'storage_manager:directory_change_name' directory_uuid=directory.uuid %}" class="px-2 mb-3">
                {% csrf_token %}
                {{ change_directory_name_form }}

                <button class="accept-button btn login-button" type="submit">
                    Update Name
                </button>
            </form>
        </div>
        <div class="content-wrapper">
            <button class="btn collapsible-primary-btn" type="button" data-bs-toggle="collapse"
                    data-bs-target="#update-directory-files" aria-expanded="false" aria-controls="update-directory-files">
                Update Files
                <img class="expand-icon" src="{% static 'icons/expand_icon.svg' %}">
            </button>
            <div class="collapse" id="update-directory-files">
              <div class="content-wrapper-collapse-content">
                  <form method="POST" action="{% url 'storage_manager:update_directory_files' directory_uuid=directory.uuid %}" class="px-2">
                    {% csrf_token %}
                    {{ update_files_form }}

                    <button class="accept-button btn login-button" type="submit">
                        Save
                    </button>
                  </form>
              </div>
            </div>
        </div>
        <div class="content-wrapper">
            <form method="POST" action="{% url 'storage_manager:share_directory_to_user' directory_uuid=directory.uuid %}" class="px-2 mb-3">
                {% csrf_token %}
                {{ share_to_user_form }}

                <button class="accept-button btn login-button" type="submit">
                    Add
                </button>
            </form>
            {% if directory.shared_to_users.all|length > 0 %}
                <button class="btn collapsible-primary-btn" type="button" data-bs-toggle="collapse"
                        data-bs-target="#shared-to-users" aria-expanded="false" aria-controls="shared-to-users">
                    Shared to users
                    <img class="expand-icon" src="{% static 'icons/expand_icon.svg' %}">
                </button>
                <div class="collapse" id="shared-to-users">
                  <div class="content-wrapper-collapse-content">
                      {% for user in directory.shared_to_users.all %}
                        <div class="shared-to-user-container">
                            <form class="w-100 d-flex" action="{% url 'storage_manager:remove_directory_from_shared' directory_uuid=directory.uuid %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="username" value="{{ user.username }}">

                                <span>{{ user.username }}</span>
                                <button class="btn remove-shared-user-btn" type="submit">
                                    <img class="expand-icon" src="{% static 'icons/close_icon.svg' %}">
                                </button>
                            </form>
                        </div>
                      {% endfor %}
                  </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

io_app/apps/storage_manager/templates/file_management.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}
    <!-- Remove Modal -->
    {% include "components/modals/remove_file_modal.html" with file=file %}

    <!-- Page content -->
    <div class="page-content-wrapper mb-3">
        <div class="content-wrapper">
            <a class="file-name" data-bs-toggle="collapse" href="#changeFileNameCollapsible" role="button"
               aria-expanded="false" aria-controls="changeFileNameCollapsible">
               <h3>{{file.name}}</h3>
            </a>
            <div class="file-details-wrapper">
              <span>
                  <b>UUID:</b> {{file.uuid}}
              </span>
              <span>
                  <b>Directory:</b> <a href="{{file.get_directory_url}}">{{file.get_directory_name}}</a>
              </span>
              <span>
                  <b>Size:</b> {{file.get_file_size_in_mb}}MB
              </span>
              <span>
                  <b>Extension:</b> {{file.extension}}
              </span>
              <span>
                  <b>Upload date:</b> {{file.upload_date|date:'d-m-Y G:i'}}
              </span>
              <span>
                  <b>Accessible via link:</b> {{file.accessible_via_link}}
              </span>
            </div>
            <div class="file-details-controls-wrapper">
              {% if file.can_be_previewed %}
                  <a class="btn btn-secondary" href="{% url 'storage_manager:preview_raw' file_uuid=file.uuid %}" role="button" target="_blank">
                      Preview
                  </a>
              {% endif %}
              <form method="POST" action="{% url 'storage_manager:toggle_access_via_link' file_uuid=file.uuid %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">
                    {% if file.accessible_via_link %}
                        Disable access via link
                    {% else %}
                        Enable access via link
                    {% endif %}
                </button>
              </form>
              <button type="button" class="btn btn-danger" data-bs-target="#removeFileModal" data-bs-toggle="modal">
                  Remove
              </button>
              <form method="GET" action="{% url 'storage_manager:download_file' file_uuid=file.uuid %}">
                <button type="submit" class="btn btn-primary">
                    Download
                </button>
              </form>
            </div>
        </div>
        <div class="content-wrapper collapse" id="changeFileNameCollapsible">
            <form method="POST" action="{% url 'storage_manager:file_change_name' file_uuid=file.uuid %}" class="px-2 mb-3">
                {% csrf_token %}
                {{ change_file_name_form }}

                <button class="accept-button btn login-button" type="submit">
                    Update Name
                </button>
            </form>
        </div>
        <div class="content-wrapper">
            <form method="POST" action="{% url 'storage_manager:change_directory' file_uuid=file.uuid %}" class="px-2">
                {% csrf_token %}
                {{ change_directory_form }}

                <button class="accept-button btn login-button" type="submit">
                    Change directory
                </button>
            </form>
        </div>
    </div>
<script src="{% static 'js/files.js' %}"></script>
{% endblock %}

io_app/apps/storage_manager/templates/file_preview.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}
    <!-- Page content -->
    <div class="page-content-wrapper mb-3">
        <div class="content-wrapper">
            <h3>{{file.name}}</h3>
            <div class="file-details-wrapper">
              <span>
                  <b>UUID:</b> {{file.uuid}}
              </span>
              <span>
                  <b>Directory:</b>{{file.get_directory_name}}
              </span>
              <span>
                  <b>Size:</b> {{file.get_file_size_in_mb}}MB
              </span>
              <span>
                  <b>Extension:</b> {{file.extension}}
              </span>
              <span>
                  <b>Upload date:</b> {{file.upload_date|date:'d-m-Y G:i'}}
              </span>
              <span>
                  <b>Accessible via link:</b> {{file.accessible_via_link}}
              </span>
            </div>
            <div class="file-details-controls-wrapper">
              {% if file.can_be_previewed %}
                  <a class="btn btn-secondary" href="{% url 'storage_manager:preview_raw' file_uuid=file.uuid %}" role="button" target="_blank">
                      Preview
                  </a>
              {% endif %}
              {% if user == file.owner %}
                  <a class="btn btn-success" href="{% url 'storage_manager:file_management' file_uuid=file.uuid %}" role="button">
                      Manage
                  </a>
              {% endif %}
              <form method="GET" action="{% url 'storage_manager:download_file' file_uuid=file.uuid %}">
                <button type="submit" class="btn btn-primary">
                    Download
                </button>
              </form>
            </div>
        </div>
    </div>
{% endblock %}

io_app/apps/storage_manager/templates/media_player.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}
    <div class="centered-container video-player-container">
        <video class="w-100" controls>
          <source src="{% url 'storage_manager:stream_media_file' file_uuid=file.uuid %}" type="video/mp4">
        </video>
    </div>
{% endblock %}

io_app/apps/storage_manager/templates/upload.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}
    <!-- Info Modal -->
    <div class="modal fade" id="uploadInfoModal" tabindex="-1" aria-labelledby="uploadInfoModal" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content info-modal-content">
          <div class="modal-header border-0">
            <h5 class="modal-title">Upload finished</h5>
          </div>
          <div class="modal-body" id="upload-info-modal-text"></div>
          <div class="modal-footer border-0">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Page content -->
    <div class="centered-container upload-container">
        <div id="file-upload-form-wrapper">
            <div class="file-upload-wrapper" id="file-upload-wrapper">
                <label for="file-upload" class="file-upload-label">
                    <img src="{% static 'icons/upload_icon.svg' %}">
                </label>
                <input id="file-upload" class="file-upload-input" type="file">
            </div>
            <span class="d-none upload-file-name-wrapper" id="upload-file-name-wrapper"></span>
            <button id="upload-button" class="btn btn-primary w-100 disabled" onclick="uploadFile('{{ upload_url }}', '{{ csrf_token }}');">
                Upload
            </button>
        </div>
        <div class="file-upload-details-wrapper d-none" id="file-upload-details-wrapper">
            <span id="upload-file-name"></span>
            <progress id="upload-file-progress" class="upload-file-progress" max="100" value="0"></progress>
            <span class="upload-file-progress-value" id="upload-file-progress-value">0%</span>
        </div>
    </div>

<script src="{% static 'js/files_upload.js' %}"></script>
<script>
    const fileInput = document.getElementById("file-upload");
    fileInput.addEventListener("change", onFileSelected);
</script>
{% endblock %}