core/urls.py
from django.urls import path
from core import views


app_name = "core"

urlpatterns = [
    path("", views.home, name="home")
]

io_app/apps/core/urls.py
from django.urls import path
from io_app.apps.core import views


app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("page/<str:page_id>/", views.home, name="home"),
    path("directories/", views.directories, name="directories"),
    path("directories/page/<str:page_id>/", views.directories, name="directories"),
    path("directories/<str:directory_uuid>/", views.directory_content, name="directory_content"),
    path("directories/<str:directory_uuid>/<str:page_id>/", views.directory_content, name="directory_content"),
    path("shared_directories/", views.shared_directories, name="shared_directories"),
    path("processes/", views.processes, name="processes"),
    path("processes/start_archive_extraction_process/start/", views.start_archive_extraction_process,
         name="start_archive_extraction_process"),
    path("processes/start_directory_compression_process/start/", views.start_directory_compression_process,
         name="start_directory_compression_process"),
    path("processes/start_video_compatibility_conversion_process/start/",
         views.start_video_compatibility_conversion_process,
         name="start_video_compatibility_conversion_process"),
]

io_app/apps/storage_manager/urls.py
from django.urls import path
from io_app.apps.storage_manager.views import files_views, directories_views


app_name = "storage_manager"

urlpatterns = [
    path("upload/", files_views.upload, name="upload"),
    path("upload_file/", files_views.upload_file, name="upload_file"),
    path("files/<str:file_uuid>/", files_views.preview, name="preview"),
    path("files/<str:file_uuid>/download/", files_views.download_file, name="download_file"),
    path("files/<str:file_uuid>/remove/", files_views.remove_file, name="remove_file"),
    path("files/<str:file_uuid>/toggle_access_via_link/", files_views.toggle_access_via_link,
         name="toggle_access_via_link"),
    path("files/<str:file_uuid>/preview/", files_views.preview_raw, name="preview_raw"),
    path("files/<str:file_uuid>/stream/", files_views.stream_media_file, name="stream_media_file"),
    path("files/<str:file_uuid>/management/", files_views.file_management, name="file_management"),
    path("files/<str:file_uuid>/change_directory/", files_views.change_directory, name="change_directory"),
    path("files/<str:file_uuid>/change_name/", files_views.file_change_name, name="file_change_name"),
    path("directories/add", directories_views.add_directory, name="add_directory"),
    path("directories/<str:directory_uuid>/management/", directories_views.directory_management,
         name="directory_management"),
    path("directories/<str:directory_uuid>/remove/", directories_views.remove_directory,
         name="remove_directory"),
    path("directories/<str:directory_uuid>/update_files/", directories_views.update_directory_files,
         name="update_directory_files"),
    path("directories/<str:directory_uuid>/share_directory_to_user/", directories_views.share_directory_to_user,
         name="share_directory_to_user"),
    path("directories/<str:directory_uuid>/remove_directory_from_shared/", directories_views.remove_directory_from_shared,
         name="remove_directory_from_shared"),
    path("directories/<str:directory_uuid>/change_name/", directories_views.directory_change_name,
         name="directory_change_name"),
]

io_app/urls.py
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path("", include("io_app.apps.core.urls")),
    path("auth/", include("io_app.apps.authenticate.urls")),
    path("storage/", include("io_app.apps.storage_manager.urls")),
    path("api/", include("io_app.apps.api.urls")),
]


if settings.DEBUG or settings.ADMIN_ENABLED:
    from django.contrib import admin

    admin.site.site_header = "IO admin"
    admin.site.index_title = "IO admin"
    admin.site.site_title = "IO admin"

    urlpatterns.append(path('admin/', admin.site.urls))


handler404 = "io_app.apps.core.error_views.not_found"
handler500 = "io_app.apps.core.error_views.server_error"
handler400 = "io_app.apps.core.error_views.bad_request"

io_app/apps/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from io_app.consts import MessagesConsts, MediaConsts
from io_app.apps.storage_manager import models


class StartArchiveExtractionProcessForm(forms.Form):
    file_name = forms.ChoiceField(label="", widget=forms.Select(attrs={
        "class": "form-select",
    }))

    template_name = "components/form.html"

    def clean_file_name(self):
        data = self.cleaned_data["file_name"]
        file = models.File.objects.filter(owner=self.user, name=data).first()

        if not file:
            raise ValidationError(MessagesConsts.FILE_DOESNT_EXIST)

        if file.extension not in MediaConsts.COMMON_ARCHIVE_EXTENSIONS:
            raise ValidationError(MessagesConsts.FILE_IS_NOT_ARCHIVE)

        return data


class StartDirectoryCompressionProcessForm(forms.Form):
    directory_name = forms.ChoiceField(label="", widget=forms.Select(attrs={
        "class": "form-select",
    }))

    template_name = "components/form.html"

    def clean_directory_name(self):
        data = self.cleaned_data["directory_name"]

        directory = models.Directory.objects.filter(owner=self.user, name=data).first()
        file = models.File.objects.filter(owner=self.user, name=directory.uuid).first()

        if not directory:
            raise ValidationError(MessagesConsts.DIRECTORY_DOESNT_EXIST)

        if file:
            raise ValidationError(MessagesConsts.ARCHIVE_FOR_DIRECTORY_EXISTS)

        return data


class StartVideoCompatibilityConversionProcessForm(forms.Form):
    file_name = forms.ChoiceField(label="", widget=forms.Select(attrs={
        "class": "form-select",
    }))

    re_encode = forms.BooleanField(label="re-encode", required=False, widget=forms.CheckboxInput(attrs={
        "class": "form-check-input"
    }))

    template_name = "components/form.html"

    def clean_file_name(self):
        data = self.cleaned_data["file_name"]
        file = models.File.objects.filter(owner=self.user, name=data).first()

        if not file:
            raise ValidationError(MessagesConsts.FILE_DOESNT_EXIST)

        if file.extension not in MediaConsts.COMMON_VIDEO_EXTENSIONS:
            raise ValidationError(MessagesConsts.FILE_IS_NOT_VIDEO)

        return data

io_app/apps/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from io_app.consts import PaginationConsts, MessagesConsts, MediaConsts
from io_app.apps.storage_manager import models
from io_app.apps.core import forms
from io_app.utils import processes_utils, files_utils


@login_required
@require_http_methods(["GET"])
def home(request, page_id=1):
    search_file_name = request.GET.get("search_file", "")

    files = request.user.files.filter(name__contains=search_file_name).order_by("-upload_date").all()
    recent_files = request.user.files.order_by("-upload_date").all()[:5]

    files_paginator = Paginator(files, PaginationConsts.FILES_PER_PAGE)
    files_page = files_paginator.get_page(page_id)

    return render(request, "home.html", {
        "recent_files": recent_files,
        "files_page": files_page,
        "search_file_name": search_file_name,
    })


@login_required
@require_http_methods(["GET"])
def directories(request, page_id=1):
    search_dir_name = request.GET.get("search_dir", "")

    directories = request.user.directories.filter(name__contains=search_dir_name).order_by("-creation_date").all()

    directories_paginator = Paginator(directories, PaginationConsts.FILES_PER_PAGE)
    directories_page = directories_paginator.get_page(page_id)

    return render(request, "directories.html", {
        "title": "My Directories",
        "directories_page": directories_page,
        "search_dir_name": search_dir_name,
    })


@login_required
@require_http_methods(["GET"])
def directory_content(request, directory_uuid, page_id=1):
    directory = get_object_or_404(models.Directory, uuid=directory_uuid)

    if request.user == directory.owner or request.user in directory.shared_to_users.all():
        search_file_name = request.GET.get("search_file", "")

        files = directory.files.filter(name__contains=search_file_name).order_by("-upload_date").all()

        files_paginator = Paginator(files, PaginationConsts.FILES_PER_PAGE)
        files_page = files_paginator.get_page(page_id)

        return render(request, "directory.html", {
            "files_page": files_page,
            "search_file_name": search_file_name,
            "directory": directory,
            "shared_view": False if request.user == directory.owner else True,
        })

    raise Http404


@login_required
@require_http_methods(["GET"])
def shared_directories(request, page_id=1):
    search_dir_name = request.GET.get("search_dir", "")

    directories = request.user.shared_directories.filter(name__contains=search_dir_name).order_by("-creation_date").all()

    directories_paginator = Paginator(directories, PaginationConsts.FILES_PER_PAGE)
    directories_page = directories_paginator.get_page(page_id)

    return render(request, "directories.html", {
        "title": "Shared Directories",
        "directories_page": directories_page,
        "search_dir_name": search_dir_name,
        "shared_view": True,
    })


@login_required
@require_http_methods(["GET"])
def processes(request):
    return render(request, "processes.html", {})


@login_required
@require_http_methods(["GET", "POST"])
def start_archive_extraction_process(request):
    form = forms.StartArchiveExtractionProcessForm(data=request.POST or None)
    form.user = request.user

    files = models.File.objects.filter(owner=request.user, directory=None).all()
    form.fields["file_name"].choices = [(file.name, file.name) for file in files]

    if request.method == "POST":
        if form.is_valid():
            file_name = form.cleaned_data["file_name"]

            file = models.File.objects.filter(owner=request.user, name=file_name).first()

            if files_utils.check_if_user_have_enough_space_for_file(request.user, file.size):
                processes_utils.start_file_process_for_user(request.user.id, "ArchiveExtraction", file.uuid)
                messages.add_message(request, messages.SUCCESS, MessagesConsts.PROCESS_STARTED_SUCCESSFULLY)

                return redirect("core:processes")

            else:
                messages.add_message(request, messages.ERROR, MessagesConsts.NOT_ENOUGH_STORAGE_FOR_OPERATION)

    return render(request, "start_process.html", {"form": form})


@login_required
@require_http_methods(["GET", "POST"])
def start_directory_compression_process(request):
    form = forms.StartDirectoryCompressionProcessForm(data=request.POST or None)
    form.user = request.user

    directories = models.Directory.objects.filter(owner=request.user).all()
    form.fields["directory_name"].choices = [(directory.name, directory.name) for directory in directories]

    if request.method == "POST":
        if form.is_valid():
            directory_name = form.cleaned_data["directory_name"]
            directory = models.Directory.objects.filter(owner=request.user, name=directory_name).first()

            directory_size = sum([file.size for file in directory.files.all()])

            if files_utils.check_if_user_have_enough_space_for_file(request.user, directory_size):
                processes_utils.start_file_process_for_user(request.user.id, "DirectoryCompression", directory.uuid)
                messages.add_message(request, messages.SUCCESS, MessagesConsts.PROCESS_STARTED_SUCCESSFULLY)

                return redirect("core:processes")

            else:
                messages.add_message(request, messages.ERROR, MessagesConsts.NOT_ENOUGH_STORAGE_FOR_OPERATION)

    return render(request, "start_process.html", {"form": form})


@login_required
@require_http_methods(["GET", "POST"])
def start_video_compatibility_conversion_process(request):
    form = forms.StartVideoCompatibilityConversionProcessForm(data=request.POST or None)
    form.user = request.user

    files = models.File.objects.filter(owner=request.user).all()
    form.fields["file_name"].choices = \
        [(file.name, file.name) for file in files if file.extension in MediaConsts.COMMON_VIDEO_EXTENSIONS]

    if request.method == "POST":
        if form.is_valid():
            file_name = form.cleaned_data["file_name"]
            re_encode = form.cleaned_data["re_encode"]
            file = models.File.objects.filter(owner=request.user, name=file_name).first()

            if files_utils.check_if_user_have_enough_space_for_file(request.user, file.size):
                processes_utils.start_file_process_for_user(request.user.id, "VideoCompatibilityConversion", file.uuid, {
                    "re_encode": re_encode,
                })

                messages.add_message(request, messages.SUCCESS, MessagesConsts.PROCESS_STARTED_SUCCESSFULLY)

                return redirect("core:processes")

            else:
                messages.add_message(request, messages.ERROR, MessagesConsts.NOT_ENOUGH_STORAGE_FOR_OPERATION)

    return render(request, "start_process.html", {"form": form})

io_app/apps/files_manager/views/directories_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from io_app.apps.files_manager import models
from io_app.consts import MessagesConsts
from io_app.apps.files_manager import forms
import logging


logger = logging.getLogger(settings.LOGGER_NAME)


@login_required
@require_http_methods(["GET", "POST"])
def add_directory(request):
    form = forms.AddDirectoryForm(data=request.POST or None)

    if request.method == "POST":
        form.user = request.user

        if form.is_valid():
            directory_name = request.POST["directory_name"]
            models.Directory(name=directory_name, owner=request.user).save()

            messages.add_message(request, messages.SUCCESS, MessagesConsts.DIRECTORY_ADDED)

            return redirect("core:directories")

    return render(request, "add_directory.html", {"form": form})


@login_required
@require_http_methods(["GET"])
def directory_management(request, directory_uuid):
    directory = get_object_or_404(models.Directory, uuid=directory_uuid, owner=request.user)

    context = {
        "directory": directory,
    }

    return render(request, "directory_management.html", context)


@login_required
@require_http_methods(["POST"])
def remove_directory(request, directory_uuid):
    directory = get_object_or_404(models.Directory, uuid=directory_uuid, owner=request.user)
    directory.delete()

    messages.add_message(request, messages.SUCCESS, MessagesConsts.DIRECTORY_REMOVED_SUCCESSFULLY)

    return redirect("core:directories")

io_app/apps/core/templates/directories.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}
    <!-- Page content -->
    <div class="page-content-wrapper mb-3">
        <!-- My Directories -->
        <div class="content-wrapper">
            <h3>
                {{ title }}
            </h3>
            <div class="mb-3">
                <form action="{% url 'core:directories' %}" method="GET">
                    {% include "components/search_bar.html" with search_value=search_dir_name search_name="search_dir" search_placeholder="search directories" %}
                </form>
            </div>
            <div class="files-container my-files-container">
                {% for directory in directories_page %}
                    <a class="file-wrapper-click" href="{% url 'core:directory_content' directory_uuid=directory.uuid %}">
                        <div class="file-wrapper">
                            <img src="{% static 'icons/folder_icon.svg' %}">
                            <span>{{ directory.name }}</span>
                        </div>
                    </a>
                {% endfor %}
            </div>
            {% if directories_page.has_next or directories_page.has_previous %}
                <div class="pagination-controls">
                    {% if directories_page.has_previous %}
                        <a class="pagination-controls-item" href="{% url 'core:directories' page_id=directories_page.previous_page_number %}">
                            <img src="{% static 'icons/navigate_before_icon.svg' %}">
                        </a>
                    {% endif %}
                    {% if files_page.has_next %}
                        <a class="pagination-controls-item {% if not directories_page.has_previous %} left-p-controls-item {% endif %}"
                           href="{% url 'core:directories' page_id=directories_page.next_page_number %}">
                            <img src="{% static 'icons/navigate_next_icon.svg' %}">
                        </a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

io_app/apps/core/templates/directory.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}
    <!-- Info Modal -->
    {% include "components/modals/info_file_modal.html" %}

    <!-- Page content -->
    <div class="page-content-wrapper mb-3">
        <!-- My Files -->
        <div class="content-wrapper">
            <h3>
                {{directory.owner.username}}/{{directory.name}}
            </h3>
            <div class="file-details-wrapper">
              <span>
                  <b>Size:</b> {{directory.get_size_in_mb}}MB</span>
              </span>
              <span>
                  <b>Files:</b> {{directory.get_files_count}}</span>
              </span>
              <span>
                  <b>Creation date:</b> {{directory.creation_date|date:'d-m-Y G:i'}}</span>
              </span>
            </div>
            {% if directory.owner == request.user %}
                <div class="mb-3 directory-controls-wrapper">
                    <a class="btn btn-success" href="{% url 'storage_manager:directory_management' directory_uuid=directory.uuid %}" role="button">
                      Manage
                    </a>
                </div>
            {% endif %}
            <div class="mb-3">
                <form action="{% url 'core:directory_content' directory_uuid=directory.uuid %}" method="GET">
                    {% include "components/search_bar.html" with search_value=search_file_name search_name="search_file" search_placeholder="search files" %}
                </form>
            </div>

            <!-- Files Preview -->
            {% include "components/files_preview.html" %}

            {% if files_page.has_next or files_page.has_previous %}
                <div class="pagination-controls">
                    {% if files_page.has_previous %}
                        <a class="pagination-controls-item" href="{% url 'core:directory_content' page_id=files_page.previous_page_number %}">
                            <img src="{% static 'icons/navigate_before_icon.svg' %}">
                        </a>
                    {% endif %}
                    {% if files_page.has_next %}
                        <a class="pagination-controls-item {% if not files_page.has_previous %} left-p-controls-item {% endif %}"
                           href="{% url 'core:directory_content' page_id=files_page.next_page_number %}">
                            <img src="{% static 'icons/navigate_next_icon.svg' %}">
                        </a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
<script src="{% static 'js/files.js' %}"></script>
{% endblock %}

io_app/apps/core/templates/error.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}

<div class="centered-container">
   <p>
        {{ error }}
    </p>
    <p>
        <a href="{% url 'core:home' %}">go home</a>
    </p>
</div>

{% endblock %}

io_app/apps/core/templates/home.html
{% extends "page_layout.html" %}
{% load core_tags %}
{% load static %}
{% block page_content %}

    <!-- Info Modal -->
    {% include "components/modals/info_file_modal.html" %}

    <!-- Page content -->
    <div class="page-content-wrapper mb-3">
        <div class="content-wrapper content-wrapper-loading" id="storage-usage-data-wrapper">
            <div id="storage-usage-data" class="d-none">
                <h3>
                    Storage usage
                </h3>
                <div class="graphs-container" id="graphs-container">
                    <div id="storage-usage" class="graph-wrapper">
                        <span id="storage-used-space-value" class="storage-used-space-value"></span>
                    </div>
                    <div id="storage-usage-by-type" class="graph-wrapper"></div>
                </div>
                {% include "components/storage_details_collapsible.html" %}
            </div>
            <div class="spinner-border text-primary" id="storage-usage-data-spinner">
              <span class="visually-hidden">Loading storage usage data</span>
            </div>
        </div>
        {% if recent_files|length > 0 %}
            <div class="content-wrapper">
                <h3>
                    Recent files
                </h3>
                <div class="files-container no-gap">
                    {% for file in recent_files %}
                        <div class="recent-file"
                             onclick="showFileInfoModal('fileInfoModal', '{{file.name}}', '{{file.get_file_size_in_mb}}',
                              '{{file.extension}}', '{{file.uuid}}', '{{file.upload_date|date:'d-m-Y G:i'}}', '{{file.get_directory_name}}',
                              '{{ file.get_directory_url }}', {% can_file_be_previewed file %});">
                            <img src="{% get_icon_for_file file %}">
                            <span>{{ file.name }}</span>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <!-- My Files -->
        <div class="content-wrapper">
            <h3>
                My files
            </h3>
            <div class="mb-3">
                <form action="{% url 'core:home' %}" method="GET">
                    {% include "components/search_bar.html" with search_value=search_file_name search_name="search_file" search_placeholder="search files" %}
                </form>
            </div>

            <!-- Files Preview -->
            {% include "components/files_preview.html" %}

            {% if files_page.has_next or files_page.has_previous %}
                <div class="pagination-controls">
                    {% if files_page.has_previous %}
                        <a class="pagination-controls-item" href="{% url 'core:home' page_id=files_page.previous_page_number %}">
                            <img src="{% static 'icons/navigate_before_icon.svg' %}">
                        </a>
                    {% endif %}
                    {% if files_page.has_next %}
                        <a class="pagination-controls-item {% if not files_page.has_previous %} left-p-controls-item {% endif %}"
                           href="{% url 'core:home' page_id=files_page.next_page_number %}">
                            <img src="{% static 'icons/navigate_next_icon.svg' %}">
                        </a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
<script src="{% static 'js/files.js' %}"></script>

<script src="{% static 'libs/chart.js' %}"
        onerror="fallbackToRemoteJS(this, 'https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.min.js');">
</script>
<script src="{% static 'js/charts_utils.js' %}"></script>

<script>
    initStorageUsageStats();
</script>
{% endblock %}

io_app/apps/core/templates/my_directories.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}
    <!-- Remove Directory Modal -->
    {% include "components/remove_directory_modal.html" %}

    <!-- Info Directory Modal -->
    {% include "components/info_directory_modal.html" %}

    <!-- Page content -->
    <div class="page-content-wrapper mb-3">
        <!-- My Directories -->
        <div class="content-wrapper">
            <h3>
                My Directories
            </h3>
            <div class="mb-3">
                <form action="{% url 'core:directories' %}" method="GET">
                    <div class="input-group">
                      <input type="text" class="form-control" value="{{search_dir_name}}"
                             name="search_dir" placeholder="directory name">
                      <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit">
                            <img src="{% static 'icons/search_icon.svg' %}" alt="search">
                        </button>
                      </div>
                    </div>
                </form>
            </div>
            <div class="files-container my-files-container">
                {% for directory in directories_page %}
                    <div class="my-file"
                         onclick="showDirectoryInfoModal('directoryInfoModal', '{{directory.name}}', '{{directory.uuid}}',
                          '{{directory.get_size_in_mb}}', '{{directory.get_files_count}}',
                          '{{directory.creation_date|date:'d-m-Y G:i'}}',
                          '#',
                          '#',
                          '{% url 'core:directory_content' directory_uuid=directory.uuid %}')">
                        <img src="{% static 'icons/folder_icon.svg' %}">
                        <span>{{ directory.name }}</span>
                    </div>
                {% endfor %}
            </div>
            {% if directories_page.has_next or directories_page.has_previous %}
                <div class="pagination-controls">
                    {% if directories_page.has_previous %}
                        <a class="pagination-controls-item" href="{% url 'core:directories' page_id=directories_page.previous_page_number %}">
                            <img src="{% static 'icons/navigate_before_icon.svg' %}">
                        </a>
                    {% endif %}
                    {% if files_page.has_next %}
                        <a class="pagination-controls-item {% if not directories_page.has_previous %} left-p-controls-item {% endif %}"
                           href="{% url 'core:directories' page_id=directories_page.next_page_number %}">
                            <img src="{% static 'icons/navigate_next_icon.svg' %}">
                        </a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
<script src="{% static 'js/directories.js' %}"></script>
{% endblock %}

io_app/apps/core/templates/processes.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}
    <div class="page-content-wrapper mb-3" id="processes-wrapper"></div>
<script src="{% static 'js/processes.js' %}"></script>
<script>
    renderRunningProcesses();
    setInterval(renderRunningProcesses, 2000);
</script>
{% endblock %}

io_app/apps/core/templates/start_process.html
{% extends "page_layout.html" %}
{% load static %}
{% block page_content %}

<div class="centered-container">
    <form method="POST">
        {% csrf_token %}
        {{ form }}

        <button class="accept-button btn login-button" type="submit">
            Run
        </button>
    </form>
</div>

{% endblock %}