authenticate/urls.py
from django.urls import path
from authenticate import views


app_name = "authenticate"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout")
]

core/urls.py
from django.urls import path
from core import views


app_name = "core"

urlpatterns = [
    path("", views.home, name="home")
]

io_app/apps/api/urls.py
from django.urls import path
from io_app.apps.api import views


app_name = "api"

urlpatterns = [
    path("storage_usage/", views.storage_usage, name="storage_usage"),
    path("storage_usage_by_filetype/", views.storage_usage_by_filetype, name="storage_usage_by_filetype"),
    path("processes/currently_running/", views.running_processes, name="running_processes"),
]

io_app/apps/core/urls.py
from django.urls import path
from io_app.apps.core import views


app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("page/<str:page_id>/", views.home, name="home"),
    path("directories/", views.directories, name="directories"),
    path("directories/page/<str:page_id>/", views.directories, name="directories"),
    path("directories/<str:directory_uuid>/", views.directory_content, name="directory_content"),
    path("directories/<str:directory_uuid>/<str:page_id>/", views.directory_content, name="directory_content"),
    path("shared_directories/", views.shared_directories, name="shared_directories"),
    path("processes/", views.processes, name="processes"),
    path("processes/start_archive_extraction_process/start/", views.start_archive_extraction_process,
         name="start_archive_extraction_process"),
    path("processes/start_directory_compression_process/start/", views.start_directory_compression_process,
         name="start_directory_compression_process"),
    path("processes/start_video_compatibility_conversion_process/start/",
         views.start_video_compatibility_conversion_process,
         name="start_video_compatibility_conversion_process"),
]

io_app/apps/storage_manager/urls.py
from django.urls import path
from io_app.apps.storage_manager.views import files_views, directories_views


app_name = "storage_manager"

urlpatterns = [
    path("upload/", files_views.upload, name="upload"),
    path("upload_file/", files_views.upload_file, name="upload_file"),
    path("files/<str:file_uuid>/", files_views.preview, name="preview"),
    path("files/<str:file_uuid>/download/", files_views.download_file, name="download_file"),
    path("files/<str:file_uuid>/remove/", files_views.remove_file, name="remove_file"),
    path("files/<str:file_uuid>/toggle_access_via_link/", files_views.toggle_access_via_link,
         name="toggle_access_via_link"),
    path("files/<str:file_uuid>/preview/", files_views.preview_raw, name="preview_raw"),
    path("files/<str:file_uuid>/stream/", files_views.stream_media_file, name="stream_media_file"),
    path("files/<str:file_uuid>/management/", files_views.file_management, name="file_management"),
    path("files/<str:file_uuid>/change_directory/", files_views.change_directory, name="change_directory"),
    path("files/<str:file_uuid>/change_name/", files_views.file_change_name, name="file_change_name"),
    path("directories/add", directories_views.add_directory, name="add_directory"),
    path("directories/<str:directory_uuid>/management/", directories_views.directory_management,
         name="directory_management"),
    path("directories/<str:directory_uuid>/remove/", directories_views.remove_directory,
         name="remove_directory"),
    path("directories/<str:directory_uuid>/update_files/", directories_views.update_directory_files,
         name="update_directory_files"),
    path("directories/<str:directory_uuid>/share_directory_to_user/", directories_views.share_directory_to_user,
         name="share_directory_to_user"),
    path("directories/<str:directory_uuid>/remove_directory_from_shared/", directories_views.remove_directory_from_shared,
         name="remove_directory_from_shared"),
    path("directories/<str:directory_uuid>/change_name/", directories_views.directory_change_name,
         name="directory_change_name"),
]

io_app/urls.py
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path("", include("io_app.apps.core.urls")),
    path("auth/", include("io_app.apps.authenticate.urls")),
    path("storage/", include("io_app.apps.storage_manager.urls")),
    path("api/", include("io_app.apps.api.urls")),
]


if settings.DEBUG or settings.ADMIN_ENABLED:
    from django.contrib import admin

    admin.site.site_header = "IO admin"
    admin.site.index_title = "IO admin"
    admin.site.site_title = "IO admin"

    urlpatterns.append(path('admin/', admin.site.urls))


handler404 = "io_app.apps.core.error_views.not_found"
handler500 = "io_app.apps.core.error_views.server_error"
handler400 = "io_app.apps.core.error_views.bad_request"

io_app/apps/api/models.py
from django.db import models

# Create your models here.

io_app/apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from io_app.apps.users.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("username",)

io_app/apps/api/views.py
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from io_app.utils import files_utils, tasks_utils
from io_app.consts import ProcessesConsts


@login_required
@require_http_methods(["GET"])
def storage_usage(request):
    used_space = files_utils.get_user_storage_size_in_mb(request.user.id)
    free_space = round((request.user.private_storage_space - used_space), 2)

    free_space = free_space if free_space >= 0 else 0

    return JsonResponse(data={
        "free_space": free_space,
        "used_space": used_space
    })


@login_required
@require_http_methods(["GET"])
def storage_usage_by_filetype(request):
    storage_usage_percentage = files_utils.get_used_storage_by_file_extension_percentage(
        request.user.id,
        request.user.files.all()
    )

    return JsonResponse(data=storage_usage_percentage)


@login_required
@require_http_methods(["GET"])
def running_processes(request):
    processes_data = tasks_utils.get_tasks_data_for_user(request.user.id)

    for data in processes_data:
        if ProcessesConsts.OWNER_ID in data.keys():
            del data[ProcessesConsts.OWNER_ID]

    return JsonResponse(data={"processes_data": processes_data})

io_app/apps/authenticate/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate as auth_user
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from io_app.apps.authenticate import forms
from io_app.consts import MessagesConsts


@require_http_methods(["GET", "POST"])
def login(request):
    if not request.user.is_authenticated:
        form = forms.LoginForm(data=request.POST or None)

        if request.method == "POST":
            if form.is_valid():
                username = form.cleaned_data["username"]
                password = form.cleaned_data["password"]

                user = auth_user(request, username=username, password=password)

                if user is not None:
                    auth_login(request, user)
                    return redirect(settings.LOGIN_REDIRECT_URL)

                messages.add_message(request, messages.ERROR, MessagesConsts.LOGIN_ERROR)

        return render(request, "login.html", {"form": form})

    else:
        return redirect(settings.LOGIN_REDIRECT_URL)


@login_required
@require_http_methods(["GET"])
def logout(request):
    auth_logout(request)

    return redirect(settings.LOGIN_REDIRECT_URL)

io_app/apps/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from io_app.consts import PaginationConsts, MessagesConsts, MediaConsts
from io_app.apps.storage_manager import models
from io_app.apps.core import forms
from io_app.utils import processes_utils, files_utils


@login_required
@require_http_methods(["GET"])
def home(request, page_id=1):
    search_file_name = request.GET.get("search_file", "")

    files = request.user.files.filter(name__contains=search_file_name).order_by("-upload_date").all()
    recent_files = request.user.files.order_by("-upload_date").all()[:5]

    files_paginator = Paginator(files, PaginationConsts.FILES_PER_PAGE)
    files_page = files_paginator.get_page(page_id)

    return render(request, "home.html", {
        "recent_files": recent_files,
        "files_page": files_page,
        "search_file_name": search_file_name,
    })


@login_required
@require_http_methods(["GET"])
def directories(request, page_id=1):
    search_dir_name = request.GET.get("search_dir", "")

    directories = request.user.directories.filter(name__contains=search_dir_name).order_by("-creation_date").all()

    directories_paginator = Paginator(directories, PaginationConsts.FILES_PER_PAGE)
    directories_page = directories_paginator.get_page(page_id)

    return render(request, "directories.html", {
        "title": "My Directories",
        "directories_page": directories_page,
        "search_dir_name": search_dir_name,
    })


@login_required
@require_http_methods(["GET"])
def directory_content(request, directory_uuid, page_id=1):
    directory = get_object_or_404(models.Directory, uuid=directory_uuid)

    if request.user == directory.owner or request.user in directory.shared_to_users.all():
        search_file_name = request.GET.get("search_file", "")

        files = directory.files.filter(name__contains=search_file_name).order_by("-upload_date").all()

        files_paginator = Paginator(files, PaginationConsts.FILES_PER_PAGE)
        files_page = files_paginator.get_page(page_id)

        return render(request, "directory.html", {
            "files_page": files_page,
            "search_file_name": search_file_name,
            "directory": directory,
            "shared_view": False if request.user == directory.owner else True,
        })

    raise Http404


@login_required
@require_http_methods(["GET"])
def shared_directories(request, page_id=1):
    search_dir_name = request.GET.get("search_dir", "")

    directories = request.user.shared_directories.filter(name__contains=search_dir_name).order_by("-creation_date").all()

    directories_paginator = Paginator(directories, PaginationConsts.FILES_PER_PAGE)
    directories_page = directories_paginator.get_page(page_id)

    return render(request, "directories.html", {
        "title": "Shared Directories",
        "directories_page": directories_page,
        "search_dir_name": search_dir_name,
        "shared_view": True,
    })


@login_required
@require_http_methods(["GET"])
def processes(request):
    return render(request, "processes.html", {})


@login_required
@require_http_methods(["GET", "POST"])
def start_archive_extraction_process(request):
    form = forms.StartArchiveExtractionProcessForm(data=request.POST or None)
    form.user = request.user

    files = models.File.objects.filter(owner=request.user, directory=None).all()
    form.fields["file_name"].choices = [(file.name, file.name) for file in files]

    if request.method == "POST":
        if form.is_valid():
            file_name = form.cleaned_data["file_name"]

            file = models.File.objects.filter(owner=request.user, name=file_name).first()

            if files_utils.check_if_user_have_enough_space_for_file(request.user, file.size):
                processes_utils.start_file_process_for_user(request.user.id, "ArchiveExtraction", file.uuid)
                messages.add_message(request, messages.SUCCESS, MessagesConsts.PROCESS_STARTED_SUCCESSFULLY)

                return redirect("core:processes")

            else:
                messages.add_message(request, messages.ERROR, MessagesConsts.NOT_ENOUGH_STORAGE_FOR_OPERATION)

    return render(request, "start_process.html", {"form": form})


@login_required
@require_http_methods(["GET", "POST"])
def start_directory_compression_process(request):
    form = forms.StartDirectoryCompressionProcessForm(data=request.POST or None)
    form.user = request.user

    directories = models.Directory.objects.filter(owner=request.user).all()
    form.fields["directory_name"].choices = [(directory.name, directory.name) for directory in directories]

    if request.method == "POST":
        if form.is_valid():
            directory_name = form.cleaned_data["directory_name"]
            directory = models.Directory.objects.filter(owner=request.user, name=directory_name).first()

            directory_size = sum([file.size for file in directory.files.all()])

            if files_utils.check_if_user_have_enough_space_for_file(request.user, directory_size):
                processes_utils.start_file_process_for_user(request.user.id, "DirectoryCompression", directory.uuid)
                messages.add_message(request, messages.SUCCESS, MessagesConsts.PROCESS_STARTED_SUCCESSFULLY)

                return redirect("core:processes")

            else:
                messages.add_message(request, messages.ERROR, MessagesConsts.NOT_ENOUGH_STORAGE_FOR_OPERATION)

    return render(request, "start_process.html", {"form": form})


@login_required
@require_http_methods(["GET", "POST"])
def start_video_compatibility_conversion_process(request):
    form = forms.StartVideoCompatibilityConversionProcessForm(data=request.POST or None)
    form.user = request.user

    files = models.File.objects.filter(owner=request.user).all()
    form.fields["file_name"].choices = \
        [(file.name, file.name) for file in files if file.extension in MediaConsts.COMMON_VIDEO_EXTENSIONS]

    if request.method == "POST":
        if form.is_valid():
            file_name = form.cleaned_data["file_name"]
            re_encode = form.cleaned_data["re_encode"]
            file = models.File.objects.filter(owner=request.user, name=file_name).first()

            if files_utils.check_if_user_have_enough_space_for_file(request.user, file.size):
                processes_utils.start_file_process_for_user(request.user.id, "VideoCompatibilityConversion", file.uuid, {
                    "re_encode": re_encode,
                })

                messages.add_message(request, messages.SUCCESS, MessagesConsts.PROCESS_STARTED_SUCCESSFULLY)

                return redirect("core:processes")

            else:
                messages.add_message(request, messages.ERROR, MessagesConsts.NOT_ENOUGH_STORAGE_FOR_OPERATION)

    return render(request, "start_process.html", {"form": form})

io_app/apps/files/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.conf import settings
from io_app.utils import files_utils
from io_app.apps.files import models
from io_app.consts import MessagesConsts
import uuid
import logging
import os


logger = logging.getLogger(settings.LOGGER_NAME)


@login_required
@require_http_methods(["GET"])
def upload(request):
    return render(request, "upload.html", {
        "upload_url": reverse("files:upload_file")
    })


@login_required
@require_http_methods(["POST"])
def upload_file(request):
    filename = request.headers["X-File-Name"]
    file_size = int(request.headers["X-File-Size"])
    file_extension = filename.split(".")[-1]

    files_utils.make_files_dir_for_user(request.user.id)

    file_uuid = str(uuid.uuid4().hex)
    file_path = os.path.join(settings.STORAGE_PATH, str(request.user.id), file_uuid)

    try:
        with open(file_path, "wb") as data:
            while True:
                file_chunk = request.read(settings.FILES_UPLOAD_CHUNK_LENGTH)

                if len(file_chunk) <= 0:
                    break

                data.write(file_chunk)

        uploaded_file_size = files_utils.get_size_of_file(file_path)

        if uploaded_file_size == file_size:
            models.File(name=filename, uuid=file_uuid, extension=file_extension,
                        size=uploaded_file_size,
                        owner_id=request.user.id).save()

            response_message = MessagesConsts.FILE_UPLOADED_SUCCESSFULLY.format(filename=filename)
            response_status = 200

        else:
            response_message = MessagesConsts.FILE_UPLOAD_FAILED_SIZE_MISMATCH
            response_status = 500

            logger.error(MessagesConsts.FILE_UPLOAD_FAILED_SIZE_MISMATCH_LOG.format(
                filename=filename, org_size=str(file_size), saved_size=str(uploaded_file_size))
            )

            files_utils.remove_user_file(request.user.id, file_uuid)

        response_data = {
            "message": response_message
        }

    except Exception as e:
        response_data = {
            "message": MessagesConsts.ERROR_WHILE_UPLOADING_FILE.format(filename=filename)
        }
        response_status = 500

        logger.error(MessagesConsts.ERROR_WHILE_UPLOADING_FILE_LOG.format(filename=filename, e=str(e)))

    finally:
        pass

    return JsonResponse(data=response_data, status=response_status)

io_app/apps/users/views.py
from django.shortcuts import render

# Create your views here.

io_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="{% static 'main.js' %}"></script>

        <link rel="stylesheet" href="{% static 'main.css' %}">
        <link href="{% static 'libs/bootstrap.min.css' %}"
              onerror="fallbackToRemoteFileLink(this, 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css');"
              rel="stylesheet"
              integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
              crossorigin="anonymous">

        <title>IO</title>
    </head>
    <body>
        {% if messages %}
            <div class="flashed-messages-container">
              {% for message in messages %}
                <div class="flashed-message-container flashed-message-container-{{ message.tags }}">
                    <span>
                        {{ message }}
                    </span>
                </div>
              {% endfor %}
            </div>
        {% endif %}
        {% block content %}
        {% endblock %}

        <script src="{% static 'libs/bootstrap.bundle.min.js' %}"
                onerror="fallbackToRemoteJS(this, 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js');"
                integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
                crossorigin="anonymous">
        </script>
    </body>
</html>

io_app/templates/page_layout.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="main-container">
    <div class="navbar main-navbar sticky-top navbar-expand-md">
        <div class="container-fluid">
            <div class="navbar-title-wrapper">
                <a class="navbar-brand navbar-logo" href="{% url 'core:home' %}">
                    <img src="{% static 'icons/io_icon.svg' %}">
                    IO
                </a>
            </div>
            {% if user.is_authenticated %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar"
                        aria-controls="mainNavbar" aria-expanded="false">

                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="mainNavbar">
                    <ul class="navbar-nav ms-auto">
                      <li class="nav-item">
                        <a class="nav-item-link" href="{% url 'storage_manager:upload' %}">
                            <img src="{% static 'icons/file_upload_icon.svg' %}">
                            <span class="nav-item-link-text">Upload File</span>
                        </a>
                      </li>
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" id="navbarProcessesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{% static 'icons/processes_icon.svg' %}">
                            <span class="nav-item-link-text">Processes</span>
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarProcessesDropdown">
                            <li><a class="dropdown-item" href="{% url 'core:processes' %}">Running Processes</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item" href="{% url 'core:start_archive_extraction_process' %}">
                                    Archive Extraction
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'core:start_directory_compression_process' %}">
                                    Directory Compression
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'core:start_video_compatibility_conversion_process' %}">
                                    Video Compatibility Conversion
                                </a>
                            </li>
                          </ul>
                      </li>
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" id="navbarFilesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{% static 'icons/files_icon.svg' %}">
                            <span class="nav-item-link-text">Files</span>
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarFilesDropdown">
                            <li><a class="dropdown-item" href="{% url 'core:home' %}">My Files</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:directories' %}">My Directories</a></li>
                            <li><a class="dropdown-item" href="{% url 'storage_manager:add_directory' %}">Create Directory</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:shared_directories' %}">Shared Directories</a></li>
                          </ul>
                      </li>
                      <li class="nav-item">
                        <a class="nav-item-link" href="{% url 'authenticate:logout' %}">
                            <img src="{% static 'icons/logout_icon.svg' %}">
                            <span class="nav-item-link-text">Logout</span>
                        </a>
                      </li>
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
    {% block page_content %}
    {% endblock %}
</div>

{% endblock %}